### PR TITLE
Added intersection-map project

### PR DESCRIPTION
**Pull request by laesser**
Full source: https://github.com/laesser/intersection-map

### CODE REVIEW

**Comment by Pomax** [comment]
It looks like https://github.com/laesser/intersection-map is a 404.

**Comment by Pomax** [comment]
@ben can you delete those DS_Store files, as well as the web fonts? Let's load those from google like everyone else. The original repo looks like it's still a 404 though, do you happen to know what the real one is?

**Comment by ayahohner** [comment]
@laesser Hi, is this PR still needed? If so, can you please add .DS_Store to your .gitignore, and swap the embedded fonts for Google Fonts? Otherwise, let me know and I can close this PR.

**Comment by laesser** [comment]
Well, its has been a while. I don't know how to start and where.

**Comment by ayahohner** [comment]
@laesser Yes it has. My apologies. I wasn't aware this was still open. 
Is this project still happening? Is it worth checking in with the team working on the intersection map? 
If it's not progressing anymore I can close the PR. Otherwise, we can get things started again, if you have the availability/budget.

**Comment by laesser** [comment]
I'm not working for the project right now. I don't have any slack contact with team and of course you can ask them if this is a important task.

**Pull request closed without merging**
