### PR TITLE
Add sunburst visualization for mozilla-fellowships-and-awards-program…

### PR DESCRIPTION
**Pull request by enabek**
…-evaluation project

[https://github.com/objectively/mofo-sunburst-visualization](https://github.com/objectively/mofo-sunburst-visualization)

### CODE REVIEW

**Comment by ayahohner** [comment]
@enabek Hi there, can you please contact your MoFo contact and have them reach out to me on Slack. We need to verify that you're a trusted MoFo contractor. Thanks!

**Review by benhohner — DISMISSED** [review]
Hi @enabek, thanks for submitting this PR, I'm going to approve this, though normally we ask to view the original source to do a security analysis, but since you've included source maps, that should be fine.

**Review by benhohner — CHANGES_REQUESTED** [review]
Hey, sorry about that, would you be able to add the project launch date to the beginning of the folder, in the format mentioned in the repo readme? Thanks!

**Review by benhohner — APPROVED** [review]
Thanks!

**Pull request merged**
